Update project to be installed and released via poetry
RedHatQE/python-simple-logger pull request #28
Opened 2023-07-31 21:00 UTC by oharan2

- Verified VERSION file
- Updated project metadata and dependencies
- Updated `poetry.lock` according new changes
- Update README

2023-08-02 12:53 UTC, rnetser requested changes
Please update PR title

2023-08-02 12:53 UTC, rnetser commented on pyproject.toml
> +target_version = ['py37', 'py38', 'py39', 'py310', "py311"]
please remove `py37`

2023-08-03 10:55 UTC, oharan2 commented
/retest python-module-install

2023-08-03 11:04 UTC, oharan2 commented
/verified

2023-08-03 13:48 UTC, myakove commented
/retest python-module-install

2023-08-03 13:49 UTC, myakove commented
/retest tox

2023-08-03 13:57 UTC, myakove commented
/retest python-module-install

2023-08-03 15:22 UTC, myakove approved these changes

2023-08-03 16:27 UTC, myakove approved these changes

2023-08-03 16:27 UTC, merged